<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * 
 * Contao extension: fussball_widget
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Martin Kozianka
 * License   : LGPL 
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
$GLOBALS['TL_LANG']['MOD']['fussball_tournament']      = array("Turnierteilnahmen", "Turnierteilnahmen");

$GLOBALS['TL_LANG']['CTE']['fussball']                 = 'Fussball';
$GLOBALS['TL_LANG']['CTE']['fussball_tournament_list'] = array('Fussball - Turnierliste', 'Turnierliste');
$GLOBALS['TL_LANG']['CTE']['fussball_goalgetter_list'] = array('Fussball - Torschützenliste', 'Torschützenliste');
$GLOBALS['TL_LANG']['CTE']['fussball_widget']          = array('Fussball - fussball.de Widget', 'Fügt das fussball.de Widget ein. Der API-Key muss in den Einstellungen hinterlegt werden.');
$GLOBALS['TL_LANG']['CTE']['fussball_highscore_graph'] = array('Fussball - Tabellenplatzentwicklung', 'Tabellenplatzentwicklung als Grafik (Google Chart Tools)');
$GLOBALS['TL_LANG']['CTE']['fussball_results']         = array('Fussball - Saisonverlauf', 'Stellt den Saisonverlauf in einer Tabelle dar.');


