<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * 
 * Contao extension: fussball_widget
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Martin Kozianka
 * License   : LGPL 
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */

$GLOBALS['TL_LANG']['CTE']['fussball_widget'] = array('fussball.de Widget', 'Fügt das fussball.de Widget ein. Der API-Key muss in den Einstellungen hinterlegt werden.');
$GLOBALS['TL_LANG']['CTE']['fussball_highscore_graph'] = array('Grafik - Tabellenplatzentwicklung', 'Tabellenplatzentwicklung als Grafik (Google Chart Tools)');


?>