<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * 
 * Contao extension: fussball_widget
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Martin Kozianka
 * License   : LGPL 
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
$GLOBALS['TL_LANG']['tl_content']['fussball_graph_legend']    = 'Tabellenplatzgrafik';
$GLOBALS['TL_LANG']['tl_content']['fussball_results_legend']  = 'Saisonverlauf';
$GLOBALS['TL_LANG']['tl_content']['fussball_widget_legend']   = 'Fussball';

$GLOBALS['TL_LANG']['tl_content']['fussball_positions']       = array('Mannschaftsname/Platzierungen', 'Schlüssel: Mannschaftname, Wert: Kommaseparierte Liste der Platzierungen (Bsp: 1,3,6,7,9,5,5,11)');
$GLOBALS['TL_LANG']['tl_content']['fussball_maxPositions']    = array('Plätze (insgesamt)', 'Anzahl der Mannschaften in der Liga');
$GLOBALS['TL_LANG']['tl_content']['fussball_graph_size']      = array('Höhe und Breite', 'Höhe und Breite der Grafik');
$GLOBALS['TL_LANG']['tl_content']['fussball_saison']          = array('Saison', 'Saisonauswahl als vierstellige Zahl (Beispiel: Saison 2010/2011 entspricht: 1011)');
$GLOBALS['TL_LANG']['tl_content']['fussball_wettbewerbs_id']  = array('ID des Wettbewerbs', 'Die ID kann man auf fussball.de nachgucken. Eine Anleitung gibt es hier: <a onclick="window.open(this.href); return false;" style="text-decoration:underline;" href="http://www.fussball.de/ergebnis-widget-fussball-de-fuer-deine-vereins-webseite-/id_17772204/index">fussball.de Widget einbauen</a>');
$GLOBALS['TL_LANG']['tl_content']['fussball_team']            = array('Name des Teams', 'Name des Teams. Wird im Widget hervorgehoben.');
$GLOBALS['TL_LANG']['tl_content']['fussball_goalgetter']      = array('Torschützen', 'Torschützen und Toranzahl eintragen. Nur ein Name pro Zeile. Die Sortierung erfolgt automatisch.');
$GLOBALS['TL_LANG']['tl_content']['fussball_gg_name']         = array('Name', 'Name');
$GLOBALS['TL_LANG']['tl_content']['fussball_gg_goals']        = array('Tore', 'Tore');

$GLOBALS['TL_LANG']['tl_content']['fussball_results']        = array('Begegnungen', 'Begegnungen');
$GLOBALS['TL_LANG']['tl_content']['fussball_is_homematch']   = array("Heimspiel?", "Ist das Spiel ein Heimspiel?");
$GLOBALS['TL_LANG']['tl_content']['fussball_opponent']       = array("Spiel", "Spiel");
$GLOBALS['TL_LANG']['tl_content']['fussball_result']         = array("Ergebnis", "Ergebnis");
