<?php if (!defined('TL_ROOT')) die('You can not access this file directly!');
/**
 * 
 * Contao extension: fussball_widget
 * Deutsch translation file 
 * 
 * Copyright : &copy; 2011 Martin Kozianka
 * License   : LGPL 
 * Author    : Martin Kozianka
 * Translator: Martin Kozianka
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 

$GLOBALS['TL_LANG']['tl_settings']['fussball_widget_legend'] = 'fussball.de Widget';
$GLOBALS['TL_LANG']['tl_settings']['fussball_api_key'] = array('API-Key', 'Wie man einen API-Key von fussball.de bekommt, kann man hier nachlesen: <a onclick="window.open(this.href); return false;" style="text-decoration:underline;" href="http://www.fussball.de/ergebnis-widget-fussball-de-fuer-deine-vereins-webseite-/id_17772204/index">fussball.de Widget</a>');

$GLOBALS['TL_LANG']['tl_content']['fussball_saison'] = array('Saison', 'Saisonauswahl 4 Ziffer (Beispiel: Saison 2010/2011 entspricht: 1011)');
$GLOBALS['TL_LANG']['tl_content']['fussball_wettbewerbs_id'] = array('ID des Wettbewerbs', 'Die ID kann man auf fussball.de nachgucken. Eine Anleitung gibt es hier: <a onclick="window.open(this.href); return false;" style="text-decoration:underline;" href="http://www.fussball.de/ergebnis-widget-fussball-de-fuer-deine-vereins-webseite-/id_17772204/index">fussball.de Widget einbauen</a>');


